CREATE TABLE users (
id UUID NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
active boolean DEFAULT FALSE,
deleted_at TIMESTAMP,
PRIMARY KEY(id));
