CREATE TABLE verification(
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
verification_code VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
expired_at TIMESTAMP,
active boolean DEFAULT true,
user_id UUID NOT NULL,
CONSTRAINT fk_user_code_id FOREIGN KEY (user_id) REFERENCES users(id),
PRIMARY KEY(id))